language: php

matrix:
  include:
    - php: 7.1
      env: deps=low
    - php: 7.2
      env: deps=low
    - php: 7.1
    - php: 7.2
  fast_finish: true

before_script:
  - sudo apt-get install mp3info 
  - composer install --dev --prefer-source
